### PR TITLE
Add hex8 color format support

### PR DESCRIPTION
**Pull request by ijse**

### CODE REVIEW

**Comment by ruhley** [comment]
I have never heard of hex8, but from what I understand the first two characters are the alpha value. The alpha field is currently disabled when the user has selected hex. I can enable it for hex formats and when the alpha is not 100% it will switch to hex8 automatically. How does that sound?

**Comment by ijse** [comment]
but what if I want the format always be hex8?

**Comment by ruhley** [comment]
That is a very valid point. Merging now.

**Comment by ruhley** [comment]
Released in [v0.4.0](https://github.com/ruhley/angular-color-picker/releases/tag/v0.4.0). Thanks for the pull request.

**Pull request merged**
