### PR TITLE
Don't attempt to hide colour picker if it's not visible

### PR DESCRIPTION
**Pull request by aaronjoslyn**
Hello,

I have some complicated pages with colour pickers on them, and whenever the user clicks anywhere on the page it triggers a digest cycle. This is a bit of a problem when combined with numeric inputs or other elements on the page which get clicked a lot :) I'm assuming this is necessary to ensure the colour picker hides though, so I was wondering if it would be possible to only trigger the cycle if the colour picker is already showing.

Thanks for your help :)

### CODE REVIEW

**Comment by aaronjoslyn** [comment]
Thanks for your quick reply. That seems to work great! The colour picker still disappears when clicking off it, and the digest cycle no longer triggers on every mouse click. If you're happy with the change, should I run a `grunt build` and get the newly generated JS committed?

**Comment by ruhley** [comment]
That would be great. Follow the [release](https://github.com/ruhley/angular-color-picker/blob/master/RELEASE.md) file if you haven't already found it. Make it v0.8.2.

Could you also run ```git rebase -i master``` to squish the current three commits down into one.

Thanks :+1:

**Comment by aaronjoslyn** [comment]
Done. Let me know if I've missed anything!

**Comment by ruhley** [comment]
Merged and released in [v0.8.2](https://github.com/ruhley/angular-color-picker/releases/tag/v0.8.2). Thanks for the pull request!

**Pull request merged**
