### PR TITLE
Enhancement - add input name and id options

### PR DESCRIPTION
**Pull request by ashconnell**
A simple change to add id and name options to set attributes on the internal input.

The id attribute is useful if you use a label:

```html
<label for="input-id">Choose a color</label>
<color-picker ng-model="color" options="{ id: 'input-id' }" />
```

The name attribute is useful for form validation and ng-messages:

```html
<form name="myForm">
    <color-picker ng-model="color" options="{ name: 'color', required: true }" />
    <ng-messages for="myForm.color.$error" role="alert">
        <ng-message when="required">This field is required</ng-message>
    </ng-messages>
</form>
```

### CODE REVIEW

**Comment by ruhley** [comment]
Hi @ashconnell ,

Thanks for the PR, just a couple of things before I merge it in. Can you add these additional options to the `options-service.js` file, and make them default to `undefined`. I believe angularjs wlll not add the attribute if the value is undefined.

**Comment by ashconnell** [comment]
@ruhley done 39b789f :)

**Comment by ruhley** [comment]
I have released v2.4.5 with this update. Thanks for the PR :+1:

**Comment by ashconnell** [comment]
@ruhley i'm not sure but thanks for creating this lib! It's clearly the best angular color picker around!

**Pull request merged**
